### ISSUE TITLE
Maps are not displayed in configured order/with configured display names

### ISSUE THREAD

**Issue by Garmelon** [BillyGalbreath/Pl3xMap#155]
My worlds are configured the following way in `config/pl3xmap/config.yml`:
```yml
<snip beginning of file with commented config options>
  world:
    enabled: true
    render:
      renderers:
        basic: overworld_basic
        night: overworld_night
        biomes: overworld_biomes
        inhabited: inhabited
        flowermap: flowermap
    ui:
      display-name: Overworld
      order: 0
  world_nether:
    render:
      renderers:
        basic: nether_basic
        night: nether_night
        biomes: nether_biomes
        inhabited: inhabited
      skylight: 0
    ui:
      display-name: The Nether
      order: 1
  world_the_end:
    render:
      renderers:
        basic: the_end_basic
        night: the_end_night
        biomes: the_end_biomes
        inhabited: inhabited
      skylight: 0
    ui:
      display-name: The End
      order: 2
```
In the browser, this is how the maps are displayed:
![image](https://github.com/BillyGalbreath/Pl3xMap/assets/11077553/900e14b7-4c3f-4d7f-9626-ff8aedd46b4b)
`the_end` is displayed above `the_nether` but its `order` field is greater than that of `the_nether`.

The configured display names are not used in the UI either.

**Comment by Garmelon** [comment]
I just noticed that my config includes a flowermap for the overworld which the web client also doesn't display as an available option.

**Comment by BillyGalbreath** [comment]
Your config is using the default Bukkit names for the worlds. Your worlds are actually named what you see, like `minecraft:overworld`. So these are what you need to use as your worlds in the config.

```yaml
  minecraft:overworld:
    enabled: true
    render:
      renderers:
        basic: overworld_basic
        night: overworld_night
        biomes: overworld_biomes
        inhabited: inhabited
        flowermap: flowermap
    ui:
      display-name: Overworld
      order: 0
  minecraft:the_nether:
    render:
      renderers:
        basic: nether_basic
        night: nether_night
        biomes: nether_biomes
        inhabited: inhabited
      skylight: 0
    ui:
      display-name: The Nether
      order: 1
  minecraft:the_end:
    render:
      renderers:
        basic: the_end_basic
        night: the_end_night
        biomes: the_end_biomes
        inhabited: inhabited
      skylight: 0
    ui:
      display-name: The End
      order: 2
```

I'll leave this open as a reminder that I still need to find a clean way to automate this depending on the platform being used.
