### ISSUE TITLE
web-address config option ignored in /pl3xmap command

### ISSUE THREAD

**Issue by Garmelon** [BillyGalbreath/Pl3xMap#156]
I've configured a web address and a nonstandard port:
```yml
settings:
  debug-mode: false
  language-file: lang-en.yml
  web-address: https://example.com/minecraft/map/
  <snip>
  internal-webserver:
    enabled: true
    bind: 0.0.0.0
    port: 8005
<snip>
```
When I run the `/pl3xmap` command on the server, the reply is
```
[Pl3xMap] View the map at 'http://localhost:8080/'
```
I expected the server to reply something like
```
[Pl3xMap] View the map at 'https://example.com/minecraft/map/'
```
