### ISSUE TITLE
New heightmap which acts like vanilla & water/lava dithering added back

### ISSUE THREAD

**Issue by zndrmn** [BillyGalbreath/Pl3xMap#175]
~~I would love it if you were able to implement a new heightmap that acts like vanilla 
(or works exactly like the already implemented vanilla renderer just not a replica of the in-game vanilla map style)~~

~~So for example the shading would be from top/down like vanilla instead of the shading being left/right like the old school heightmap.
The heightmap could be called something like "vanilla" or "vanilla-esque" heightmap~~

Also it would be great if you added back the vanilla water/lava dithering which could be toggled per-dimension.
All of these features would epic af if you implement them, especially the last one (option for per-dimension heightmaps)

<br>
<br>

It would be interesting if you could add the ability to change the heightmap per-dimension because then you could add options like this

```yml
  minecraft:overworld:
    enabled: true
    dithering:
      water: true
      lava: false
    heightmap: overworld_vanilla_esque
    render:
      renderers:
        basic: overworld_basic
        night: overworld_night
        biomes: overworld_biomes
        inhabited: inhabited
        flowermap: flowermap
    ui:
      display-name: Overworld
      order: 0
  minecraft:the_nether:
    dithering:
      water: false
      lava: true
    heightmap: nether_modern
    render:
      renderers:
        basic: nether_basic
        night: nether_night
        biomes: nether_biomes
        inhabited: inhabited
      skylight: 0
    ui:
      display-name: The Nether
      order: 1
  minecraft:the_end:
    dithering:
      water: false
      lava: false
    heightmap: the_end_old_school
    render:
      renderers:
        basic: the_end_basic
        night: the_end_night
        biomes: the_end_biomes
        inhabited: inhabited
      skylight: 0
    ui:
      display-name: The End
      order: 2
```
